/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2023-03-10 00:28:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class side_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/tiles-jsp-2.2.2.jar", Long.valueOf(1655775970791L));
    _jspx_dependants.put("jar:file:/C:/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/bookShop01/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1655775966109L));
    _jspx_dependants.put("jar:file:/C:/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/bookShop01/WEB-INF/lib/tiles-jsp-2.2.2.jar!/META-INF/tld/tiles-jsp.tld", Long.valueOf(1276606224000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav>\r\n");
      out.write("<ul>\r\n");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("	\r\n");
      out.write("</ul>\r\n");
      out.write("</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/common/side.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/common/side.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/common/side.jsp(6,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('\r');
          out.write('\n');
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/common/side.jsp(17,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${side_menu=='admin_mode' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("   <li>\r\n");
          out.write("		<H3>관리자</H3>\r\n");
          out.write("		<ul>\r\n");
          out.write("			<li><a href=\"#\">등록 회원 조회</a></li>\r\n");
          out.write("			<li><a href=\"#\">등록 사업체 조회</a></li>\r\n");
          out.write("			<li><a href=\"#\">상품 조회</a></li>\r\n");
          out.write("			<li><a href=\"#\">문의 내역</a></li>\r\n");
          out.write("			<li><a href=\"#\">신고 내역</a></li>\r\n");
          out.write("			<li><a href=\"#\">전체 주문 조회</a></li>\r\n");
          out.write("			<li><a href=\"#\">매출 관리</a></li>\r\n");
          out.write("			<li><a href=\"#\">이벤트 관리</a></li>\r\n");
          out.write("			<li><a href=\"#\">관리자 게시물 등록</a></li>\r\n");
          out.write("		</ul>\r\n");
          out.write("	</li>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/common/side.jsp(33,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${side_menu=='my_page' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	<li>\r\n");
          out.write("		<h3>마이페이지</h3>\r\n");
          out.write("		<ul>\r\n");
          out.write("			<li><a href=\"#\">기본 정보</a></li>\r\n");
          out.write("			<li><a href=\"#\">회원 정보 수정</a></li>\r\n");
          out.write("			<li><a href=\"#\">장바구니</a></li>\r\n");
          out.write("			<li><a href=\"#\">구매 내역</a></li>\r\n");
          out.write("			<li><a href=\"#\">문의 내역</a></li>\r\n");
          out.write("			<li><a href=\"#\">주문 조회</a></li>\r\n");
          out.write("			<li><a href=\"#\">My 포인트</a></li>\r\n");
          out.write("			<li><a href=\"#\">My 게시글 조회</a></li>\r\n");
          out.write("			<li><a href=\"#\">회원 탈퇴</a></li>\r\n");
          out.write("		</ul>\r\n");
          out.write("	</li>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f2_reused = false;
    try {
      _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/common/side.jsp(49,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${side_menu=='company_page' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
      if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	<li>\r\n");
          out.write("		<h3>마이페이지</h3>\r\n");
          out.write("		<ul>\r\n");
          out.write("			<li><a href=\"#\">기본 정보</a></li>\r\n");
          out.write("			<li><a href=\"#\">회원 정보 수정</a></li>\r\n");
          out.write("			<li><a href=\"#\">상품 문의 내역</a></li>\r\n");
          out.write("			<li><a href=\"#\">판매 내역</a></li>\r\n");
          out.write("			<li><a href=\"#\">스케줄 관리</a></li>\r\n");
          out.write("			<li><a href=\"#\">My 상품 조회</a></li>\r\n");
          out.write("			<li><a href=\"#\">My 게시글 조회</a></li>\r\n");
          out.write("			<li><a href=\"#\">회원 탈퇴</a></li>\r\n");
          out.write("		</ul>\r\n");
          out.write("	</li>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      _jspx_th_c_005fwhen_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	<li>\r\n");
          out.write("		<h3>디자인</h3>\r\n");
          out.write("		<ul>\r\n");
          out.write("			<li><a href=\"#\">인쇄/홍보물</a></li>\r\n");
          out.write("			<li><a href=\"#\">패키지/커버/로고</a></li>\r\n");
          out.write("			<li><a href=\"#\">웹/모바일</a></li>\r\n");
          out.write("			<li><a href=\"#\">브랜딩/마케팅</a></li>\r\n");
          out.write("			<li><a href=\"#\">산업/제품디자인</a></li>\r\n");
          out.write("			<li><a href=\"#\">캐릭터/일러스트</a></li>\r\n");
          out.write("			<li><a href=\"#\">캘리그라피/폰트</a></li>\r\n");
          out.write("			<li><a href=\"#\">공간/건축</a></li>\r\n");
          out.write("			<li><a href=\"#\">패션/텍스타일</a></li>\r\n");
          out.write("			<li><a href=\"#\">기타</a></li>\r\n");
          out.write("		</ul>\r\n");
          out.write("	</li>\r\n");
          out.write("	<li>\r\n");
          out.write("		<h3>IT/프로그래밍</h3>\r\n");
          out.write("		<ul>\r\n");
          out.write("			<li><a href=\"#\">UX기획</a></li>\r\n");
          out.write("			<li><a href=\"#\">웹</a></li>\r\n");
          out.write("			<li><a href=\"#\">커머스</a></li>\r\n");
          out.write("			<li><a href=\"#\">모바일</a></li>\r\n");
          out.write("			<li><a href=\"#\">프로그램</a></li>\r\n");
          out.write("			<li><a href=\"#\">트렌드</a></li>\r\n");
          out.write("			<li><a href=\"#\">데이터</a></li>\r\n");
          out.write("			<li><a href=\"#\">기타</a></li>\r\n");
          out.write("		</ul>\r\n");
          out.write("	</li>\r\n");
          out.write("	<li>\r\n");
          out.write("		<h3>영상/사진/음향</h3>\r\n");
          out.write("		<ul>\r\n");
          out.write("			<li><a href=\"#\">영상</a></li>\r\n");
          out.write("			<li><a href=\"#\">사진</a></li>\r\n");
          out.write("			<li><a href=\"#\">음향</a></li>\r\n");
          out.write("			<li><a href=\"#\">엔터테이너</a></li>\r\n");
          out.write("			<li><a href=\"#\">기타</a></li>\r\n");
          out.write("		</ul>\r\n");
          out.write("	</li>\r\n");
          out.write("	<li>\r\n");
          out.write("		<h3>마케팅</h3>\r\n");
          out.write("		<ul>\r\n");
          out.write("			<li><a href=\"#\">채널 활성화</a></li>\r\n");
          out.write("			<li><a href=\"#\">바이럴/체험단</a></li>\r\n");
          out.write("			<li><a href=\"#\">업종/목적별</a></li>\r\n");
          out.write("			<li><a href=\"#\">최적화 노출</a></li>\r\n");
          out.write("			<li><a href=\"#\">광고(퍼포먼스)</a></li>\r\n");
          out.write("			<li><a href=\"#\">PR/행사</a></li>\r\n");
          out.write("			<li><a href=\"#\">분석/전략</a></li>\r\n");
          out.write("			<li><a href=\"#\">옥외/인쇄/방송 광고</a></li>\r\n");
          out.write("			<li><a href=\"#\">해외 마케팅</a></li>\r\n");
          out.write("			<li><a href=\"#\">기타</a></li>\r\n");
          out.write("		</ul>\r\n");
          out.write("	</li>\r\n");
          out.write("	<li>\r\n");
          out.write("		<h3>문서/번역</h3>\r\n");
          out.write("		<ul>\r\n");
          out.write("			<li><a href=\"#\">비즈니스/카피</a></li>\r\n");
          out.write("			<li><a href=\"#\">마케팅 글쓰기</a></li>\r\n");
          out.write("			<li><a href=\"#\">콘텐츠 글쓰기</a></li>\r\n");
          out.write("			<li><a href=\"#\">스토리텔링</a></li>\r\n");
          out.write("			<li><a href=\"#\">타이핑/첨삭</a></li>\r\n");
          out.write("			<li><a href=\"#\">번역/통역</a></li>\r\n");
          out.write("			<li><a href=\"#\">기타</a></li>\r\n");
          out.write("		</ul>\r\n");
          out.write("	</li>\r\n");
          out.write("	<li>\r\n");
          out.write("		<h3>경영자문/운영지원</h3>\r\n");
          out.write("		<ul>\r\n");
          out.write("			<li><a href=\"#\">사업계획</a></li>\r\n");
          out.write("			<li><a href=\"#\">스타트업 자문</a></li>\r\n");
          out.write("			<li><a href=\"#\">기업 자문</a></li>\r\n");
          out.write("			<li><a href=\"#\">업종별 창업</a></li>\r\n");
          out.write("			<li><a href=\"#\">비즈니스 문서</a></li>\r\n");
          out.write("			<li><a href=\"#\">기타</a></li>\r\n");
          out.write("		</ul>\r\n");
          out.write("	</li>\r\n");
          out.write("	<li>\r\n");
          out.write("		<h3>주문제작</h3>\r\n");
          out.write("		<ul>\r\n");
          out.write("			<li><a href=\"#\">인쇄/판촉물</a></li>\r\n");
          out.write("			<li><a href=\"#\">시공</a></li>\r\n");
          out.write("			<li><a href=\"#\">기타</a></li>\r\n");
          out.write("		</ul>\r\n");
          out.write("	</li>\r\n");
          out.write("	<li>\r\n");
          out.write("		<h3>세무/법무/노무</h3>\r\n");
          out.write("		<ul>\r\n");
          out.write("			<li><a href=\"#\">법무</a></li>\r\n");
          out.write("			<li><a href=\"#\">세무/회계</a></li>\r\n");
          out.write("			<li><a href=\"#\">지식재산권 보호</a></li>\r\n");
          out.write("			<li><a href=\"#\">노무</a></li>\r\n");
          out.write("			<li><a href=\"#\">기타</a></li>\r\n");
          out.write("		</ul>\r\n");
          out.write("	</li>\r\n");
          out.write("	<li>\r\n");
          out.write("		<h3>취업/입시/노하우/직무역량</h3>\r\n");
          out.write("		<ul>\r\n");
          out.write("			<li><a href=\"#\">취업/이직</a></li>\r\n");
          out.write("			<li><a href=\"#\">입시/자격증</a></li>\r\n");
          out.write("			<li><a href=\"#\">투잡/재테크</a></li>\r\n");
          out.write("			<li><a href=\"#\">전자책/VOD</a></li>\r\n");
          out.write("			<li><a href=\"#\">데이터/개발 레슨</a></li>\r\n");
          out.write("			<li><a href=\"#\">실무/자기개발 레슨</a></li>\r\n");
          out.write("			<li><a href=\"#\">외국어 레슨</a></li>\r\n");
          out.write("			<li><a href=\"#\">디자인/영상 레슨</a></li>\r\n");
          out.write("			<li><a href=\"#\">기타</a></li>\r\n");
          out.write("		</ul>\r\n");
          out.write("	</li>\r\n");
          out.write("	<li>\r\n");
          out.write("		<h3>취미/생활</h3>\r\n");
          out.write("		<ul>\r\n");
          out.write("			<li><a href=\"#\">뷰티/운동</a></li>\r\n");
          out.write("			<li><a href=\"#\">댄스/뮤직</a></li>\r\n");
          out.write("			<li><a href=\"#\">미술/글쓰기</a></li>\r\n");
          out.write("			<li><a href=\"#\">공예/취미</a></li>\r\n");
          out.write("			<li><a href=\"#\">웨딩</a></li>\r\n");
          out.write("			<li><a href=\"#\">청소/수리/설치</a></li>\r\n");
          out.write("			<li><a href=\"#\">기타</a></li>\r\n");
          out.write("		</ul>\r\n");
          out.write("	</li>\r\n");
          out.write(" ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
